{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "720d3cac-9133-4f26-b955-67c61ba09218",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "🚀 Training XGBoost Models for All Insurance Domains...\n",
      "\n",
      "============================================================\n",
      "MODEL 1: HEALTHCARE FRAUD DETECTION\n",
      "============================================================\n",
      "Healthcare Train: (5410, 2)\n",
      "Healthcare Test: (1353, 1)\n",
      "Target column: PotentialFraud\n",
      "Unique values: ['No' 'Yes' nan]\n",
      "After conversion: [0 1]\n",
      "X_health shape: (6763, 1), y_health unique: [0 1]\n",
      "Training healthcare model...\n",
      "✅ Healthcare Model:\n",
      "   Accuracy: 0.9254\n",
      "   AUC-ROC: 0.6617\n",
      "   Saved: models/xgboost_health_fraud.bin\n",
      "\n",
      "============================================================\n",
      "MODEL 2: VEHICLE INSURANCE FRAUD DETECTION\n",
      "============================================================\n",
      "Vehicle Insurance: (15420, 33)\n",
      "Target column: FraudFound_P\n",
      "Unique values: [0 1]\n",
      "X_vehicle shape: (15420, 32), y_vehicle unique: [0 1]\n",
      "Training vehicle model...\n",
      "✅ Vehicle Model:\n",
      "   Accuracy: 0.9442\n",
      "   AUC-ROC: 0.9460\n",
      "   Saved: models/xgboost_vehicle_fraud.bin\n",
      "\n",
      "============================================================\n",
      "MODEL 3: AUTO INSURANCE FRAUD\n",
      "============================================================\n",
      "Auto Insurance: (1000, 40)\n",
      "Target column: fraud_reported\n",
      "Unique values: ['Y' 'N']\n",
      "X_auto shape: (1000, 39), y_auto unique: [1 0]\n",
      "Training auto insurance model...\n",
      "✅ Auto Insurance Model:\n",
      "   Accuracy: 0.8150\n",
      "   AUC-ROC: 0.8430\n",
      "   Saved: models/xgboost_auto_fraud.bin\n",
      "\n",
      "============================================================\n",
      "✅ ALL MODELS TRAINED!\n",
      "============================================================\n",
      "\n",
      "Summary:\n",
      "  🏥 Healthcare Fraud Model:    Accuracy=92.54% | AUC=0.6617\n",
      "  🚗 Vehicle Fraud Model:       Accuracy=94.42% | AUC=0.9460\n",
      "  📋 Auto Insurance Model:      Accuracy=81.50% | AUC=0.8430\n",
      "\n",
      "Ready for Flask API deployment!\n",
      "\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import xgboost as xgb\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.preprocessing import LabelEncoder\n",
    "from sklearn.metrics import classification_report, roc_auc_score, accuracy_score\n",
    "import os\n",
    "import pickle\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "print(\"🚀 Training XGBoost Models for All Insurance Domains...\\n\")\n",
    "\n",
    "# ============================================\n",
    "# MODEL 1: HEALTHCARE FRAUD DETECTION\n",
    "# ============================================\n",
    "print(\"=\" * 60)\n",
    "print(\"MODEL 1: HEALTHCARE FRAUD DETECTION\")\n",
    "print(\"=\" * 60)\n",
    "\n",
    "try:\n",
    "    # Load healthcare training data\n",
    "    health_train = pd.read_csv('datasets/healthcare_fraud/Train-1542865627584.csv')\n",
    "    health_test = pd.read_csv('datasets/healthcare_fraud/Test-1542969243754.csv')\n",
    "    \n",
    "    print(f\"Healthcare Train: {health_train.shape}\")\n",
    "    print(f\"Healthcare Test: {health_test.shape}\")\n",
    "    \n",
    "    # Merge train + test\n",
    "    health_combined = pd.concat([health_train, health_test], ignore_index=True)\n",
    "    \n",
    "    # Find fraud column\n",
    "    fraud_col = None\n",
    "    for col in health_combined.columns:\n",
    "        if 'fraud' in col.lower() or 'potential' in col.lower():\n",
    "            fraud_col = col\n",
    "            break\n",
    "    \n",
    "    if fraud_col is None:\n",
    "        fraud_col = health_combined.columns[-1]\n",
    "    \n",
    "    print(f\"Target column: {fraud_col}\")\n",
    "    print(f\"Unique values: {health_combined[fraud_col].unique()}\")\n",
    "    \n",
    "    # Convert to binary (ensure only 0 and 1)\n",
    "    health_combined[fraud_col] = health_combined[fraud_col].apply(\n",
    "        lambda x: 1 if x in [1, 'Yes', 'yes', 'YES', True] else 0\n",
    "    )\n",
    "    \n",
    "    print(f\"After conversion: {health_combined[fraud_col].unique()}\")\n",
    "    \n",
    "    # Encode categorical\n",
    "    for col in health_combined.select_dtypes(include=['object']).columns:\n",
    "        if col != fraud_col:\n",
    "            le = LabelEncoder()\n",
    "            health_combined[col] = le.fit_transform(health_combined[col].astype(str))\n",
    "    \n",
    "    # Handle missing values\n",
    "    health_combined = health_combined.fillna(health_combined.mean(numeric_only=True))\n",
    "    \n",
    "    # Prepare features & target\n",
    "    X_health = health_combined.drop([fraud_col], axis=1, errors='ignore')\n",
    "    y_health = health_combined[fraud_col].astype(int)\n",
    "    \n",
    "    print(f\"X_health shape: {X_health.shape}, y_health unique: {y_health.unique()}\")\n",
    "    \n",
    "    X_train_h, X_test_h, y_train_h, y_test_h = train_test_split(\n",
    "        X_health, y_health, test_size=0.2, random_state=42, stratify=y_health\n",
    "    )\n",
    "    \n",
    "    # Train model\n",
    "    model_health = xgb.XGBClassifier(\n",
    "        max_depth=6,\n",
    "        learning_rate=0.1,\n",
    "        n_estimators=100,\n",
    "        objective='binary:logistic',\n",
    "        eval_metric='logloss',\n",
    "        random_state=42\n",
    "    )\n",
    "    \n",
    "    print(\"Training healthcare model...\")\n",
    "    model_health.fit(X_train_h, y_train_h, verbose=False)\n",
    "    \n",
    "    # Evaluate - handle both binary and multiclass\n",
    "    y_pred_h = model_health.predict(X_test_h)\n",
    "    y_pred_proba_h = model_health.predict_proba(X_test_h)[:, 1]\n",
    "    accuracy_h = accuracy_score(y_test_h, y_pred_h)\n",
    "    \n",
    "    try:\n",
    "        auc_h = roc_auc_score(y_test_h, y_pred_proba_h)\n",
    "    except:\n",
    "        auc_h = 0.0\n",
    "    \n",
    "    print(f\"✅ Healthcare Model:\")\n",
    "    print(f\"   Accuracy: {accuracy_h:.4f}\")\n",
    "    print(f\"   AUC-ROC: {auc_h:.4f}\")\n",
    "    \n",
    "    # Save model\n",
    "    model_health.save_model('models/xgboost_health_fraud.bin')\n",
    "    print(f\"   Saved: models/xgboost_health_fraud.bin\")\n",
    "\n",
    "except Exception as e:\n",
    "    print(f\"⚠️  Healthcare model error: {e}\")\n",
    "    accuracy_h = 0\n",
    "    auc_h = 0\n",
    "\n",
    "# ============================================\n",
    "# MODEL 2: VEHICLE/AUTO INSURANCE FRAUD\n",
    "# ============================================\n",
    "print(\"\\n\" + \"=\" * 60)\n",
    "print(\"MODEL 2: VEHICLE INSURANCE FRAUD DETECTION\")\n",
    "print(\"=\" * 60)\n",
    "\n",
    "try:\n",
    "    # Load vehicle data\n",
    "    vehicle_data = pd.read_csv('datasets/vehicle_insurance/fraud_oracle.csv')\n",
    "    print(f\"Vehicle Insurance: {vehicle_data.shape}\")\n",
    "    \n",
    "    # Find fraud column\n",
    "    fraud_col_vehicle = None\n",
    "    for col in vehicle_data.columns:\n",
    "        if 'fraud' in col.lower():\n",
    "            fraud_col_vehicle = col\n",
    "            break\n",
    "    \n",
    "    if fraud_col_vehicle is None:\n",
    "        fraud_col_vehicle = vehicle_data.columns[-1]\n",
    "    \n",
    "    print(f\"Target column: {fraud_col_vehicle}\")\n",
    "    print(f\"Unique values: {vehicle_data[fraud_col_vehicle].unique()}\")\n",
    "    \n",
    "    # Convert to binary\n",
    "    vehicle_data[fraud_col_vehicle] = vehicle_data[fraud_col_vehicle].apply(\n",
    "        lambda x: 1 if x in [1, 'Yes', 'yes', 'YES', True, 'Y'] else 0\n",
    "    )\n",
    "    \n",
    "    # Encode categorical\n",
    "    for col in vehicle_data.select_dtypes(include=['object']).columns:\n",
    "        if col != fraud_col_vehicle:\n",
    "            le = LabelEncoder()\n",
    "            vehicle_data[col] = le.fit_transform(vehicle_data[col].astype(str))\n",
    "    \n",
    "    # Handle missing values\n",
    "    vehicle_data = vehicle_data.fillna(vehicle_data.mean(numeric_only=True))\n",
    "    \n",
    "    # Prepare features & target\n",
    "    X_vehicle = vehicle_data.drop([fraud_col_vehicle], axis=1, errors='ignore')\n",
    "    y_vehicle = vehicle_data[fraud_col_vehicle].astype(int)\n",
    "    \n",
    "    print(f\"X_vehicle shape: {X_vehicle.shape}, y_vehicle unique: {y_vehicle.unique()}\")\n",
    "    \n",
    "    X_train_v, X_test_v, y_train_v, y_test_v = train_test_split(\n",
    "        X_vehicle, y_vehicle, test_size=0.2, random_state=42, stratify=y_vehicle\n",
    "    )\n",
    "    \n",
    "    # Train model\n",
    "    model_vehicle = xgb.XGBClassifier(\n",
    "        max_depth=6,\n",
    "        learning_rate=0.1,\n",
    "        n_estimators=100,\n",
    "        objective='binary:logistic',\n",
    "        eval_metric='logloss',\n",
    "        random_state=42\n",
    "    )\n",
    "    \n",
    "    print(\"Training vehicle model...\")\n",
    "    model_vehicle.fit(X_train_v, y_train_v, verbose=False)\n",
    "    \n",
    "    # Evaluate\n",
    "    y_pred_v = model_vehicle.predict(X_test_v)\n",
    "    y_pred_proba_v = model_vehicle.predict_proba(X_test_v)[:, 1]\n",
    "    accuracy_v = accuracy_score(y_test_v, y_pred_v)\n",
    "    \n",
    "    try:\n",
    "        auc_v = roc_auc_score(y_test_v, y_pred_proba_v)\n",
    "    except:\n",
    "        auc_v = 0.0\n",
    "    \n",
    "    print(f\"✅ Vehicle Model:\")\n",
    "    print(f\"   Accuracy: {accuracy_v:.4f}\")\n",
    "    print(f\"   AUC-ROC: {auc_v:.4f}\")\n",
    "    \n",
    "    # Save model\n",
    "    model_vehicle.save_model('models/xgboost_vehicle_fraud.bin')\n",
    "    print(f\"   Saved: models/xgboost_vehicle_fraud.bin\")\n",
    "\n",
    "except Exception as e:\n",
    "    print(f\"⚠️  Vehicle model error: {e}\")\n",
    "    accuracy_v = 0\n",
    "    auc_v = 0\n",
    "\n",
    "# ============================================\n",
    "# MODEL 3: AUTO INSURANCE FRAUD\n",
    "# ============================================\n",
    "print(\"\\n\" + \"=\" * 60)\n",
    "print(\"MODEL 3: AUTO INSURANCE FRAUD\")\n",
    "print(\"=\" * 60)\n",
    "\n",
    "try:\n",
    "    # Load auto data\n",
    "    auto_data = pd.read_csv('datasets/auto_insurance/insurance_claims.csv')\n",
    "    print(f\"Auto Insurance: {auto_data.shape}\")\n",
    "    \n",
    "    # Find fraud column\n",
    "    fraud_col_auto = None\n",
    "    for col in auto_data.columns:\n",
    "        if 'fraud' in col.lower():\n",
    "            fraud_col_auto = col\n",
    "            break\n",
    "    \n",
    "    if fraud_col_auto is None:\n",
    "        fraud_col_auto = auto_data.columns[-1]\n",
    "    \n",
    "    print(f\"Target column: {fraud_col_auto}\")\n",
    "    print(f\"Unique values: {auto_data[fraud_col_auto].unique()}\")\n",
    "    \n",
    "    # Convert to binary\n",
    "    auto_data[fraud_col_auto] = auto_data[fraud_col_auto].apply(\n",
    "        lambda x: 1 if x in [1, 'Yes', 'yes', 'YES', True, 'Y'] else 0\n",
    "    )\n",
    "    \n",
    "    # Encode categorical\n",
    "    for col in auto_data.select_dtypes(include=['object']).columns:\n",
    "        if col != fraud_col_auto:\n",
    "            le = LabelEncoder()\n",
    "            auto_data[col] = le.fit_transform(auto_data[col].astype(str))\n",
    "    \n",
    "    # Handle missing values\n",
    "    auto_data = auto_data.fillna(auto_data.mean(numeric_only=True))\n",
    "    \n",
    "    # Prepare features & target\n",
    "    X_auto = auto_data.drop([fraud_col_auto], axis=1, errors='ignore')\n",
    "    y_auto = auto_data[fraud_col_auto].astype(int)\n",
    "    \n",
    "    print(f\"X_auto shape: {X_auto.shape}, y_auto unique: {y_auto.unique()}\")\n",
    "    \n",
    "    X_train_a, X_test_a, y_train_a, y_test_a = train_test_split(\n",
    "        X_auto, y_auto, test_size=0.2, random_state=42, stratify=y_auto\n",
    "    )\n",
    "    \n",
    "    # Train model\n",
    "    model_auto = xgb.XGBClassifier(\n",
    "        max_depth=6,\n",
    "        learning_rate=0.1,\n",
    "        n_estimators=100,\n",
    "        objective='binary:logistic',\n",
    "        eval_metric='logloss',\n",
    "        random_state=42\n",
    "    )\n",
    "    \n",
    "    print(\"Training auto insurance model...\")\n",
    "    model_auto.fit(X_train_a, y_train_a, verbose=False)\n",
    "    \n",
    "    # Evaluate\n",
    "    y_pred_a = model_auto.predict(X_test_a)\n",
    "    y_pred_proba_a = model_auto.predict_proba(X_test_a)[:, 1]\n",
    "    accuracy_a = accuracy_score(y_test_a, y_pred_a)\n",
    "    \n",
    "    try:\n",
    "        auc_a = roc_auc_score(y_test_a, y_pred_proba_a)\n",
    "    except:\n",
    "        auc_a = 0.0\n",
    "    \n",
    "    print(f\"✅ Auto Insurance Model:\")\n",
    "    print(f\"   Accuracy: {accuracy_a:.4f}\")\n",
    "    print(f\"   AUC-ROC: {auc_a:.4f}\")\n",
    "    \n",
    "    # Save model\n",
    "    model_auto.save_model('models/xgboost_auto_fraud.bin')\n",
    "    print(f\"   Saved: models/xgboost_auto_fraud.bin\")\n",
    "\n",
    "except Exception as e:\n",
    "    print(f\"⚠️  Auto insurance model error: {e}\")\n",
    "    accuracy_a = 0\n",
    "    auc_a = 0\n",
    "\n",
    "# ============================================\n",
    "# SUMMARY\n",
    "# ============================================\n",
    "print(\"\\n\" + \"=\" * 60)\n",
    "print(\"✅ ALL MODELS TRAINED!\")\n",
    "print(\"=\" * 60)\n",
    "print(f\"\"\"\n",
    "Summary:\n",
    "  🏥 Healthcare Fraud Model:    Accuracy={accuracy_h:.2%} | AUC={auc_h:.4f}\n",
    "  🚗 Vehicle Fraud Model:       Accuracy={accuracy_v:.2%} | AUC={auc_v:.4f}\n",
    "  📋 Auto Insurance Model:      Accuracy={accuracy_a:.2%} | AUC={auc_a:.4f}\n",
    "\n",
    "Ready for Flask API deployment!\n",
    "\"\"\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cb381aba-5cc2-4360-be41-3aa7172bbda3",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.19"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
